<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RMV.Optimization.TSP.Algorithms\RMV.Optimization.TSP.Algorithms.csproj" />
    <ProjectReference Include="..\RMV.Optimization.TSP.Common\RMV.Optimization.TSP.Common\RMV.Optimization.TSP.Common.csproj" />
    <ProjectReference Include="..\RMV.Optimization.TSP.Domain\RMV.Optimization.TSP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TspUI.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MapControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>